# Generated by Django 4.1.5 on 2023-02-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('your_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='title',
        ),
    ]
